### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs constantly failing

### ISSUE THREAD

**Issue by jazizka** [microsoft/powerapps-tools#672]
**Description**
We are configuring CoE for the first time and the "[Child] Admin | Sync Logs" flow always fail.

**Component**
 - Solution [CenterofExcellenceAuditLogs_1_3_2_managed]
 - Version [e.g. 1.3.2]
 - Flow [Child] Admin | Sync Logs

**Steps to reproduce the behavior:**
Start the "Admin | Sync Audit Logs" and wait for it to fail. It turns out it is caused by its child flow.

**Screenshots**
The "Admin | Sync Audit Logs" result
![image](https://user-images.githubusercontent.com/75126976/103798212-ac63fa00-5049-11eb-8a32-0e24960ae399.png)

Few clusters of the "[Child] Admin | Sync Logs" always fail.
![image](https://user-images.githubusercontent.com/75126976/103798386-e9c88780-5049-11eb-9b47-2a5544a2b386.png)

Parse JSON step output:
`[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[54].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[54].ClientIP",
    "schemaId": "#/items/properties/ClientIP",
    "errorType": "type",
    "childErrors": []
  },`

The rest of the flow:
![image](https://user-images.githubusercontent.com/75126976/103798831-8d199c80-504a-11eb-8369-270edf681d7d.png)

Any idea what is wrong?
Thank you

**Comment by manuelap-msft** [comment]
Could you share what the GetContentDetails output looks like before the failure? This is what is parsed afterwards. Please make sure to remove sensitive information before pasting the output here.

**Comment by osbornecc** [comment]
I was getting this same error on solution version 1.3.2.  It appeared to only happen if the audit log detail contained an operation that used "ClientIPs" instead of "ClientIP" in the results schema.  When I looked at that particular JSON, yes it shows ClientIP as null but ClientIPs was an array.

It was only on a specific log operation that was not related to PowerApps/Automate activities.  I have not updated the Audit Log solution to the new version yet (still working on the Core Components).

I hope this helps.
Thanks

**Comment by jazizka** [comment]
Hi, thanks for your feedback. I am uploading output information...I changed, emails, IP and tenantID

[Outputs.txt](https://github.com/microsoft/powerapps-tools/files/5780259/Outputs.txt)


> I was getting this same error on solution version 1.3.2. It appeared to only happen if the audit log detail contained an operation that used "ClientIPs" instead of "ClientIP" in the results schema. When I looked at that particular JSON, yes it shows ClientIP as null but ClientIPs was an array.
> 
> It was only on a specific log operation that was not related to PowerApps/Automate activities. I have not updated the Audit Log solution to the new version yet (still working on the Core Components).
> 
> I hope this helps.
> Thanks

I searched for ClientIPs but I found none. Only ClientIP.

Thank you
J.

**Comment by manuelap-msft** [comment]
Thank you both, that is really helpful! Looks like the Audit Log event schema is different in some tenants or for certain events that we can't repo in our development tenant. We are actually not using the ClientIP/ClientIPs data, so I think I can update the Parse JSON to ignore this field entirely. I will get back to you in a few hours, once I have tested this.

**Comment by manuelap-msft** [comment]
Would you be able to help me test something, as I can't repo this in my development tenant.

Can you edit the [Child] Admin | Sync Logs and navigate to the Parse JSON action
![image](https://user-images.githubusercontent.com/55705669/103922025-198b9400-510b-11eb-934d-8a2418bdf7da.png)

and replace the Schema that's currently there with this one:
```
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "OrganizationId": {
                "type": "string"
            },
            "RecordType": {
                "type": "integer"
            },
            "ResultStatus": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            },
            "UserType": {
                "type": "integer"
            },
            "Version": {
                "type": "integer"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "CrmOrganizationUniqueName": {
                "type": "string"
            },
            "Fields": {
                "type": "array"
            },
            "InstanceUrl": {
                "type": "string"
            },
            "ItemType": {
                "type": "string"
            },
            "ItemUrl": {
                "type": "string"
            },
            "UserAgent": {
                "type": "string"
            },
            "CorrelationId": {
                "type": "string"
            },
            "EntityId": {
                "type": "string"
            },
            "EntityName": {
                "type": "string"
            },
            "Message": {
                "type": "string"
            },
            "PrimaryFieldValue": {
                "type": "string"
            },
            "Query": {
                "type": "string"
            },
            "QueryResults": {
                "type": "string"
            },
            "ServiceContextId": {
                "type": "string"
            },
            "ServiceContextIdType": {
                "type": "string"
            },
            "ServiceName": {
                "type": "string"
            },
            "SystemUserId": {
                "type": "string"
            },
            "UserUpn": {
                "type": "string"
            },
            "AdditionalInfo": {
                "type": "string"
            },
            "Name": {
                "type": "string"
            }
        }
    }
}
```

I removed the ClientIP/ClientIPs attribute from the JSON as we are not using the data so can safely ignore it. Please save the flow and wait for the next run to see if that solves the issue and completes successfully for you!

Thank you

**Comment by jazizka** [comment]
Hi Manuela,
I used your JSON but it failed again. So I checked the JSON output of the failed cluster. I found **"ResultStatus":null**
`{"Activity":"ConnectFromExternalApplication","Id":"9faa99d4-2c66-42f0-8e04-4dacca1f4507","RecordType":20,"CreationTime":"2021-01-07T06:59:42","Operation":"ConnectFromExternalApplication","OrganizationId":"00000000-0000-0000-0000-00000000","UserType":0,"UserKey":"john.doe@contoso.com","Workload":"AS","ResultStatus":null,"UserId":"john.doe@contoso.com","ClientIP":null,"CustomData":""}`

So, I removed ResultStatus from JSON as well. We triggered the flow 3times within 15mins and it finished successfully.

We have a question now. What is the impact of removed elements? Can it cause any issues later?

Thanks
Jakub

**Comment by manuelap-msft** [comment]
Hello,

thank you, that's great news - this won't have an impact later on, the only fields we use to update the Audit Log table are these ones:

```
 "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            },
```
The ResultStatus field is not one we use.

The initial schema was put together based on a sample of an Audit Log event, under the assumption that the schema for Audit Log event is consistent. As that's not the case, I'll work on updating the Parse JSON schema to only require fields we use later on and remove all optional fields we don't. 

Thank you for your help in testing this!

**Comment by jazizka** [comment]
Hello Manuela,
the flow executes successfully since last week. It is solved.

Thank you for your help,
Jakub

**Comment by manuelap-msft** [comment]
Great news, thanks for letting me know! I will make the same update in the next version then to ensure future customers don't experience the same issue. Thank you for your help in testing this!

**Comment by aschauera** [comment]
It seems that chaning the "type":"string" to "type":"[string,null]" in the schema to make the fields nullable also resolves the issue

**Comment by lcimon** [comment]
Hi @manuelap-msft,

I'm still facing this issue in the v1.3.5. Parse JSON Schema isn't updated as you mentioned. Once done, it works well.

**Comment by JeneferM-MSFT** [comment]
When you updated, did you check to remove unmanaged layers from the flow? 
This is described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). 

Unfortunately, if unmanaged layers exist you wont see the changes from the updated install.

**Comment by lcimon** [comment]
I well check to remove unmanaged layers. I just cross-checked again and I'm still see the full json schema instead of the one proposed by Manuela.

**Comment by JeneferM-MSFT** [comment]
re-opening as it seems the fix may not have gone out.

**Comment by JeneferM-MSFT** [comment]
validated on another install that this change is live
